# Generated by Django 2.2.16 on 2022-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DateTimeField(help_text='Дата выхода'),
        ),
    ]
