# Generated by Django 2.2.16 on 2022-08-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20220812_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(help_text='Средний рейтинг произведения', null=True, verbose_name='Рейтинг'),
        ),
    ]
