# Generated by Django 2.2.16 on 2022-08-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20220812_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id']},
        ),
    ]
