# Generated by Django 2.2.16 on 2022-08-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_title_rating'),
        ('categories', '0005_auto_20220815_0012'),
    ]

    operations = [
    ]
