# Generated by Django 2.2.16 on 2022-08-18 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_merge_20220815_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Дата выхода', validators=[django.core.validators.MaxValueValidator(2022, message='Работы из будущего не принимаются')]),
        ),
    ]
