# Generated by Django 2.2.16 on 2022-08-17 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_auto_20220815_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='1 это минимальная оценка, 1 за старание автору:)'), django.core.validators.MaxValueValidator(10, message='Он/она так хорош/а??? но 10 максимум:(')], verbose_name='Оценка'),
        ),
    ]
